//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.3

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "categories")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub name: String,
    pub description: Option<String>,
    pub category_type: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::stock_drinks::Entity")]
    StockDrinks,
    #[sea_orm(has_many = "super::stock_foods::Entity")]
    StockFoods,
}

impl Related<super::stock_drinks::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StockDrinks.def()
    }
}

impl Related<super::stock_foods::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StockFoods.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
