//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.3

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "order_items")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub order_id: Uuid,
    pub stock_drink_id: Option<Uuid>,
    pub stock_food_id: Option<Uuid>,
    pub item_type: String,
    pub price: Decimal,
    pub quantity: i32,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::orders::Entity",
        from = "Column::OrderId",
        to = "super::orders::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Orders,
    #[sea_orm(
        belongs_to = "super::stock_drinks::Entity",
        from = "Column::StockDrinkId",
        to = "super::stock_drinks::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    StockDrinks,
    #[sea_orm(
        belongs_to = "super::stock_foods::Entity",
        from = "Column::StockFoodId",
        to = "super::stock_foods::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    StockFoods,
}

impl Related<super::orders::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Orders.def()
    }
}

impl Related<super::stock_drinks::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StockDrinks.def()
    }
}

impl Related<super::stock_foods::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StockFoods.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
